Repository keyboardio/Kaleidoscope, pull requests merged in 2019-12, with the labels that each got.

#722 Dygma Raise support
  src/Kaleidoscope-Hardware-Dygma-Raise.h
  src/kaleidoscope/device/dygma/Raise.cpp
  src/kaleidoscope/device/dygma/Raise.h
  src/kaleidoscope/device/dygma/raise/Focus.cpp
  src/kaleidoscope/device/dygma/raise/Focus.h
  src/kaleidoscope/device/dygma/raise/Hand.cpp
  src/kaleidoscope/device/dygma/raise/Hand.h
  src/kaleidoscope/device/dygma/raise/SideFlash.h
  src/kaleidoscope/device/dygma/raise/TWI.cpp
  src/kaleidoscope/device/dygma/raise/TWI.h
  src/kaleidoscope/driver/bootloader/samd/Bossac.h
  src/kaleidoscope/driver/color/GammaCorrection.h
  src/kaleidoscope/driver/mcu/SAMD.h
  src/kaleidoscope/driver/storage/Flash.h
  src/kaleidoscope/util/crc16.h
  src/kaleidoscope/util/flasher/Base.h
  src/kaleidoscope/util/flasher/KeyboardioI2CBootloader.h
Labels: enhancement, plugin:hardware

#735 Added a template hook that enables compile-time sketch exploration
  examples/Internal/Sketch_Exploration/Makefile
  examples/Internal/Sketch_Exploration/Sketch_Exploration.ino
  src/kaleidoscope/Kaleidoscope.cpp
  src/kaleidoscope/Kaleidoscope.h
  src/kaleidoscope/event_handlers.h
  src/kaleidoscope/hooks.cpp
  src/kaleidoscope/hooks.h
  src/kaleidoscope/layers.cpp
  src/kaleidoscope/layers.h
  src/kaleidoscope/macro_helpers.h
  src/kaleidoscope_internal/LEDModeManager.h
  src/kaleidoscope_internal/event_dispatch.h
  src/kaleidoscope_internal/eventhandler_signature_check.h
  src/kaleidoscope_internal/sketch_exploration/keymap_exploration.h
  src/kaleidoscope_internal/sketch_exploration/plugin_exploration.h
  src/kaleidoscope_internal/sketch_exploration/sketch_exploration.h
  src/kaleidoscope_internal/type_traits/has_method.h
Labels: enhancement

#741 util/flasher/Base.h: Don't use an unnamed struct
  src/kaleidoscope/util/flasher/Base.h
Labels: bug, pending, plugin:hardware

#753 device/Raise: Fix the column loop in actOnMatrixScan()
  src/kaleidoscope/device/dygma/Raise.cpp
Labels: bug, pending, plugin:hardware

#734 New plugin: DynamicTapDance
  doc/plugin/DynamicTapDance.md
  examples/Keystrokes/DynamicTapDance/DynamicTapDance.ino
  src/Kaleidoscope-DynamicTapDance.h
  src/kaleidoscope/plugin/DynamicTapDance.cpp
  src/kaleidoscope/plugin/DynamicTapDance.h
Labels: enhancement, pending, plugin:eeprom, plugin:tapdance

#765 examples/AppSwitcher: Do not use dynamic vars in MACRO()
  examples/Features/AppSwitcher/Macros.cpp
Labels: bug

#760 Add HID short name overrides
  src/kaleidoscope/device/ATmega32U4Keyboard.h
  src/kaleidoscope/device/Base.h
  src/kaleidoscope/device/dygma/Raise.h
  src/kaleidoscope/device/ez/ErgoDox.h
  src/kaleidoscope/device/kbdfans/KBD4x.h
  src/kaleidoscope/device/keyboardio/Imago.h
  src/kaleidoscope/device/keyboardio/Model01.h
  src/kaleidoscope/device/olkb/Planck.h
  src/kaleidoscope/device/softhruf/Splitography.h
  src/kaleidoscope/device/technomancy/Atreus.h
  src/kaleidoscope/device/technomancy/Atreus2.h
  src/kaleidoscope/layers.h
  src/kaleidoscope_internal/shortname.h
Labels: enhancement, pending, plugin:hardware

#771 Replace the HID facade with a HID driver
  doc/plugin/OneShot.md
  doc/plugin/Syster.md
  examples/Keystrokes/Syster/Syster.ino
  src/Kaleidoscope.h
  src/kaleidoscope/Runtime.cpp
  src/kaleidoscope/Runtime.h
  src/kaleidoscope/device/Base.h
  src/kaleidoscope/device/dygma/Raise.cpp
  src/kaleidoscope/device/dygma/Raise.h
  src/kaleidoscope/device/ez/ErgoDox.cpp
  src/kaleidoscope/device/ez/ErgoDox.h
  src/kaleidoscope/device/keyboardio/Model01.cpp
  src/kaleidoscope/device/keyboardio/Model01.h
  src/kaleidoscope/driver/hid/Base.h
  src/kaleidoscope/driver/hid/Keyboardio.h
  src/kaleidoscope/driver/hid/base/AbsoluteMouse.h
  src/kaleidoscope/driver/hid/base/Keyboard.h
  src/kaleidoscope/driver/hid/base/Mouse.h
  src/kaleidoscope/driver/hid/keyboardio/AbsoluteMouse.h
  src/kaleidoscope/driver/hid/keyboardio/Keyboard.h
  src/kaleidoscope/driver/hid/keyboardio/Mouse.h
  src/kaleidoscope/driver/keyscanner/ATmega.h
  src/kaleidoscope/hid.h
  src/kaleidoscope/key_defs.h
  src/kaleidoscope/key_events.cpp
  src/kaleidoscope/plugin/Cycle.cpp
  src/kaleidoscope/plugin/DynamicMacros.cpp
  src/kaleidoscope/plugin/DynamicTapDance.cpp
  src/kaleidoscope/plugin/HardwareTestMode.cpp
  src/kaleidoscope/plugin/LED-ActiveModColor.cpp
  src/kaleidoscope/plugin/Macros.cpp
  src/kaleidoscope/plugin/MouseKeys.cpp
  src/kaleidoscope/plugin/MouseKeys/MouseWrapper.cpp
  src/kaleidoscope/plugin/MouseKeys/MouseWrapper.h
  src/kaleidoscope/plugin/ShapeShifter.cpp
  src/kaleidoscope/plugin/SpaceCadet.cpp
  src/kaleidoscope/plugin/Syster.cpp
  src/kaleidoscope/plugin/TapDance.cpp
  src/kaleidoscope/plugin/TopsyTurvy.cpp
  src/kaleidoscope/plugin/Turbo.cpp
  src/kaleidoscope/plugin/Unicode.cpp
  src/kaleidoscope_internal/deprecations.h
Labels: enhancement

#778 Tweak blazing trail decay
  src/kaleidoscope/plugin/LED-Stalker.cpp
Labels: enhancement, leds
