Repository keyboardio/Kaleidoscope, pull requests merged in 2021-06, with the labels that each got.

#1033 Fix Syster translation of `Key_0` to ASCII
  plugins/Kaleidoscope-Syster/src/kaleidoscope/plugin/Syster.cpp
  tests/issues/1032/1032.ino
  tests/issues/1032/sketch.json
  tests/issues/1032/test.ktest
Labels: bug

#1052 driver::hid::base: Add isKeyPressed() to the NoKeyboard classes
  src/kaleidoscope/driver/hid/base/Keyboard.h
Labels: bug

#1056 Add testcase for issue 984
  tests/issues/984/984.ino
  tests/issues/984/sketch.json
  tests/issues/984/test.ktest
Labels: plugin:oneshot

#1058 Add testcases for issues reported to Chrysalis
  tests/issues/1057/1057.ino
  tests/issues/1057/common.h
  tests/issues/1057/sketch.json
  tests/issues/1057/test.ktest
Labels: testing

#1059 Add a few explanatory comments to Qukeys example sketch
  examples/Keystrokes/Qukeys/Qukeys.ino
Labels: docs

#1050 Add plugin authors' guide document
  docs/customization/plugin-authors-guide.md
Labels: docs, plugin

#1060 Assorted portability fixes
  plugins/Kaleidoscope-Hardware-Dygma-Raise/src/kaleidoscope/device/dygma/Raise.h
  src/kaleidoscope/device/ATmega32U4Keyboard.h
  src/kaleidoscope/device/Base.h
  src/kaleidoscope/device/virtual/Virtual.h
  src/kaleidoscope/driver/hid/base/Keyboard.h
  src/kaleidoscope/driver/hid/base/Mouse.h
  src/kaleidoscope/driver/hid/keyboardio/Mouse.h
  src/kaleidoscope_internal/LEDModeManager.h
Labels: enhancement

#1067 Unicode: Update the README with Windows instructions
  plugins/Kaleidoscope-Unicode/README.md
Labels: bug, docs, pending, plugin

#1066 Unicode: Use the numpad to input digits on Linux too
  plugins/Kaleidoscope-Unicode/src/kaleidoscope/plugin/Unicode.cpp
Labels: bug, pending, plugin

#1065 Unicode: Allow setting the key used for starting Unicode input on Linux
  plugins/Kaleidoscope-Unicode/src/kaleidoscope/plugin/Unicode.cpp
  plugins/Kaleidoscope-Unicode/src/kaleidoscope/plugin/Unicode.h
Labels: bug, pending, plugin

#1068 Migrate from hostos::OSX to hostos::MACOS
  examples/Features/AppSwitcher/AppSwitcher.cpp
  plugins/Kaleidoscope-HostOS/README.md
  plugins/Kaleidoscope-HostOS/src/kaleidoscope/plugin/HostOS.h
  plugins/Kaleidoscope-Unicode/src/kaleidoscope/plugin/Unicode.cpp
Labels: enhancement, pending, plugin

#1054 Change default value of `KeyEvent::key` from `Key_NoKey` to `Key_Undefined`
  src/kaleidoscope/KeyAddrEventQueue.h
  src/kaleidoscope/KeyEvent.h
  src/kaleidoscope/Runtime.cpp
  src/kaleidoscope/key_defs.h
Labels: design-change

#1040 Add CharShift plugin
  docs/NEWS.md
  examples/Keystrokes/CharShift/CharShift.ino
  examples/Keystrokes/CharShift/sketch.json
  plugins/Kaleidoscope-CharShift/README.md
  plugins/Kaleidoscope-CharShift/library.properties
  plugins/Kaleidoscope-CharShift/src/Kaleidoscope-CharShift.h
  plugins/Kaleidoscope-CharShift/src/kaleidoscope/plugin/CharShift.cpp
  plugins/Kaleidoscope-CharShift/src/kaleidoscope/plugin/CharShift.h
  plugins/Kaleidoscope-Ranges/src/Kaleidoscope-Ranges.h
  tests/issues/1010/test/testcase.cpp
  tests/plugins/CharShift/basic/basic.ino
  tests/plugins/CharShift/basic/sketch.json
  tests/plugins/CharShift/basic/test.ktest
Labels: enhancement, plugin
