Repository keyboardio/Kaleidoscope, pull requests merged in 2022-10, with the labels that each got.

#1257 HostPowerManagement: Lift out the suspension check, to remove code duplication
  plugins/Kaleidoscope-HostPowerManagement/src/kaleidoscope/plugin/HostPowerManagement.cpp
  plugins/Kaleidoscope-HostPowerManagement/src/kaleidoscope/plugin/HostPowerManagement.h
Labels: enhancement

#1252 New plugin: LEDBrightnessConfig
  plugins/Kaleidoscope-LEDBrightnessConfig/README.md
  plugins/Kaleidoscope-LEDBrightnessConfig/library.properties
  plugins/Kaleidoscope-LEDBrightnessConfig/src/Kaleidoscope-LEDBrightnessConfig.h
  plugins/Kaleidoscope-LEDBrightnessConfig/src/kaleidoscope/plugin/LEDBrightnessConfig.cpp
  plugins/Kaleidoscope-LEDBrightnessConfig/src/kaleidoscope/plugin/LEDBrightnessConfig.h
  src/kaleidoscope/plugin/LEDControl.h
Labels: enhancement, leds, plugin

#1264 Refactor MouseKeysConfig to use focus helper functions
  plugins/Kaleidoscope-MouseKeys/README.md
  plugins/Kaleidoscope-MouseKeys/src/kaleidoscope/plugin/MouseKeysConfig.cpp
Labels: enhancement, plugin

#1269 Layer system bug fixes
  src/kaleidoscope/layers.cpp
  src/kaleidoscope/layers.h
Labels: bug

#1277 OneShot: Add an optional OneShotConfig plugin
  plugins/Kaleidoscope-OneShot/README.md
  plugins/Kaleidoscope-OneShot/src/kaleidoscope/plugin/OneShot.cpp
  plugins/Kaleidoscope-OneShot/src/kaleidoscope/plugin/OneShot.h
  plugins/Kaleidoscope-OneShot/src/kaleidoscope/plugin/OneShotConfig.cpp
Labels: enhancement, plugin

#1288 IdleLEDs: Set the default limit in PersistentIdleLEDs correctly
  plugins/Kaleidoscope-IdleLEDs/src/kaleidoscope/plugin/IdleLEDs.cpp
Labels: bug

#1293 Firmware sync
  examples/Devices/EZ/ErgoDox/ErgoDox.ino
  examples/Devices/EZ/ErgoDox/sketch.json
  examples/Devices/Keyboardio/Atreus/Atreus.ino
  examples/Devices/Keyboardio/Model01/Model01.ino
  examples/Devices/Keyboardio/Model100/Model100.ino
  examples/Devices/SOFTHRUF/Splitography/Splitography.ino
  examples/Devices/Technomancy/Atreus/Atreus.ino
Labels: enhancement, hardware
